Gorilla Context Memory leak
heketi/heketi pull request #1799
Opened 2020-10-31 08:49 UTC by alenavorozhbieva

### What does this PR achieve? Why do we need it?
Using gorilla/context leads to memory leaks on go version more than 1.7. https://github.com/gorilla/context.

### Does this PR fix issues?
fixes #1777 

Fixes #
In this MR I changed gorilla context to http.Request.Context()

### Notes for the reviewer

2020-10-31 14:30 UTC, phlogistonjohn commented
/ok to test

2020-11-02 05:34 UTC, iamniting commented
Hi @alenavorozhbieva Thanks for the PR. We do have some guidelines for commits. You can refer to below link for it.

https://github.com/heketi/heketi/blob/master/docs/contributing.md

pls squash commit 3 and 4 into one.

for apps files component should be apps, for middleware it should be Middleware and for test files it should be Test

2020-11-02 05:35 UTC, iamniting requested changes

2020-11-02 05:35 UTC, iamniting commented on apps/glusterfs/app_middleware.go
> +	data := ctx.Value("jwt")
This can be replaced with 

`r.Context().Value("jwt")`

2020-11-02 13:35 UTC, phlogistonjohn commented
Thanks a ton for pursuing this! So far on a quick glance this looks pretty simple which is encouraging. As @iamniting mentioned we generally want the patches that make up a PR to encapsulate a single logical change, as well as work stand alone. In your case this basically means squashing them together.  If you are unsure about how to do that or uncomfortable with git, etc. please just let us know and we'll try to help out on that front.

2020-11-02 14:45 UTC, alenavorozhbieva commented
I squashed two commits and changed the commits' messages

2020-11-02 15:27 UTC, phlogistonjohn commented
I think that instead of "escape of" in the commit messages something like "stop" would be more grammatical, and thus clearer, english. For example the first commit would read: "middleware: stop using gorilla context".
Thanks!

2020-11-02 15:34 UTC, phlogistonjohn commented
The changes with titles of "formatting" and "refactoring" (after the topics) should be squashed into the matching patch of the original set of three. After that I think we'll be OK on the patch structuring and we can give a proper review!

2020-11-02 16:42 UTC, izachinyaev reviewed
Looks good

2020-11-05 10:11 UTC, alenavorozhbieva commented
Can you please check now?

2020-11-05 10:36 UTC, iamniting commented
retest this please

2020-11-10 14:13 UTC, phlogistonjohn approved these changes
LGTM. Thanks so much for looking into this.

2020-11-10 14:21 UTC, iamniting approved these changes

2020-11-26 08:25 UTC, mykaul commented
What prevents this from merge?

2020-11-27 17:10 UTC, raghavendra-talur approved these changes

2020-11-27 17:10 UTC, merged

2020-11-27 17:13 UTC, raghavendra-talur commented
> What prevents this from merge?

@phlogistonjohn was waiting for my review and it slipped my mind.