Replace github.com/form3tech-oss/jwt-go with https://github.com/golang-jwt/jwt
heketi/heketi pull request #1872
Opened 2021-07-29 18:59 UTC by Haimantika

Made some changes to the required files.

Signed-off-by: Haimantika Mitra <haimantikamitra@gmail.com>

### What does this PR achieve? Why do we need it?
Switches from github.com/form3tech-oss/jwt-go to https://github.com/golang-jwt/jwt

### Does this PR fix issues?

Fixes #

### Notes for the reviewer

2021-07-30 10:02 UTC, Haimantika commented
> Can one of the admins verify this patch?

Yeah it will be great then!

2021-08-02 12:21 UTC, humblec commented
/ok-to-test

2021-08-03 13:44 UTC, phlogistonjohn commented
On first pass the PR looks OK. However, we were already in the midst of an effort to move to go modules such that heketi will be continue to be build-able on future versions of Go where only modules are supported. As such, could I please bother you to either rebase your patches on top of the work in PR #1867  or just hang in there until we've finalized go modules and merged the PR?

Thanks!

2021-08-03 15:46 UTC, Haimantika commented
> On first pass the PR looks OK. However, we were already in the midst of an effort to move to go modules such that heketi will be continue to be build-able on future versions of Go where only modules are supported. As such, could I please bother you to either rebase your patches on top of the work in PR #1867 or just hang in there until we've finalized go modules and merged the PR?
> 
> Thanks!

Both of it is do-able, however I feel the later is more suitable? I am a beginner in this, so whatever you suggest is better, we can go ahead with it?

2021-08-03 17:36 UTC, phlogistonjohn commented
> Both of it is do-able, however I feel the later is more suitable? I am a beginner in this, so whatever you suggest is better, we can go ahead with it?

Agreed. If no one is in a big rush the latter is certainly the simplest and easiest option. I suggest subscribing to PR #1867 so you can be alerted to changes on it but I'll also try to drop a reminder here. Thank you.

2021-08-05 07:12 UTC, iamniting commented
@Haimantika Can you also update the commit something like below?

```
godeps: replace "form3tech-oss/jwt-go" with "golang-jwt/jwt"

use a community maintained fork of jwt
for reference: https://github.com/kubernetes/kubernetes/issues/104007
```

2021-08-05 07:55 UTC, Haimantika commented
> @Haimantika Can you also update the commit something like below?
> 
> ```
> godeps: replace "form3tech-oss/jwt-go" with "golang-jwt/jwt"
> 
> use a community maintained fork of jwt
> for reference: https://github.com/kubernetes/kubernetes/issues/104007
> ```

Hey! Do you mean the commit message?

2021-08-05 07:58 UTC, iamniting commented
> > @Haimantika Can you also update the commit something like below?
> > ```
> > godeps: replace "form3tech-oss/jwt-go" with "golang-jwt/jwt"
> > 
> > use a community maintained fork of jwt
> > for reference: https://github.com/kubernetes/kubernetes/issues/104007
> > ```
> 
> Hey! Do you mean the commit message?

yes

2021-08-05 08:13 UTC, Haimantika commented
> > > @Haimantika Can you also update the commit something like below?
> > > ```
> > > godeps: replace "form3tech-oss/jwt-go" with "golang-jwt/jwt"
> > > 
> > > use a community maintained fork of jwt
> > > for reference: https://github.com/kubernetes/kubernetes/issues/104007
> > > ```
> > 
> > 
> > Hey! Do you mean the commit message?
> 
> yes

Just changed, does it look fine now?

2021-08-05 08:19 UTC, iamniting commented
> > > > @Haimantika Can you also update the commit something like below?
> > > > ```
> > > > godeps: replace "form3tech-oss/jwt-go" with "golang-jwt/jwt"
> > > > 
> > > > use a community maintained fork of jwt
> > > > for reference: https://github.com/kubernetes/kubernetes/issues/104007
> > > > ```
> > > 
> > > 
> > > Hey! Do you mean the commit message?
> > 
> > 
> > yes
> 
> Just changed, does it look fine now?

Not really, the header of your commit-msg is too long, it should exactly look like mines. Do not repeat the body twice in the header and body.
![Screenshot from 2021-08-05 13-47-21](https://user-images.githubusercontent.com/22993933/128316690-3a231e25-4cff-4453-bf1c-64e1a0078d4b.png)
.

2021-08-05 08:23 UTC, Haimantika commented
> > > > > @Haimantika Can you also update the commit something like below?
> > > > > ```
> > > > > godeps: replace "form3tech-oss/jwt-go" with "golang-jwt/jwt"
> > > > > 
> > > > > use a community maintained fork of jwt
> > > > > for reference: https://github.com/kubernetes/kubernetes/issues/104007
> > > > > ```
> > > > 
> > > > 
> > > > Hey! Do you mean the commit message?
> > > 
> > > 
> > > yes
> > 
> > 
> > Just changed, does it look fine now?
> 
> Not really, the header of your commit-msg is too long, it should exactly look like mines. Do not repeat the body twice in the header and body.
> ![Screenshot from 2021-08-05 13-47-21](https://user-images.githubusercontent.com/22993933/128316690-3a231e25-4cff-4453-bf1c-64e1a0078d4b.png)

Oops! My bad! Fixed it now!

2021-08-05 08:24 UTC, iamniting commented
The commit-msg looks good to me now. As https://github.com/heketi/heketi/pull/1867 is merged you can rebase and make appropriate changes. We will CI after that.

2021-08-05 08:26 UTC, Haimantika commented
> The commit-msg looks good to me now. As #1867 is merged you can rebase and make appropriate changes. We will run CI after that.

I did this yesterday itself.

2021-08-05 08:28 UTC, iamniting commented
> > The commit-msg looks good to me now. As #1867 is merged you can rebase and make appropriate changes. We will run CI after that.
> 
> I did this yesterday itself.

We no longer need glide.yaml, moreover you need to make changes to go.mod and go.sum

2021-08-05 08:29 UTC, Haimantika commented
> > > The commit-msg looks good to me now. As #1867 is merged you can rebase and make appropriate changes. We will run CI after that.
> > 
> > 
> > I did this yesterday itself.
> 
> We no longer need glide.yaml, moreover you need to make changes to go.mod and go.sum

Yeah. The glide.yaml file I removed. Looks like it did not work! Let me try again and update you here.

2021-08-05 09:13 UTC, Haimantika commented
> > > The commit-msg looks good to me now. As #1867 is merged you can rebase and make appropriate changes. We will run CI after that.
> > 
> > 
> > I did this yesterday itself.
> 
> We no longer need glide.yaml, moreover you need to make changes to go.mod and go.sum

Does it look good now?

However why am I seeing this? Will this affect in any way?
![Capture](https://user-images.githubusercontent.com/32809211/128324824-9f0787b5-6220-4be4-862f-9eb37ab0fd74.PNG)

2021-08-05 09:25 UTC, iamniting commented
> > > > The commit-msg looks good to me now. As #1867 is merged you can rebase and make appropriate changes. We will run CI after that.
> > > 
> > > 
> > > I did this yesterday itself.
> > 
> > 
> > We no longer need glide.yaml, moreover you need to make changes to go.mod and go.sum
> 
> Does it look good now?
> 
> However why am I seeing this? Will this affect in any way?
> ![Capture](https://user-images.githubusercontent.com/32809211/128324824-9f0787b5-6220-4be4-862f-9eb37ab0fd74.PNG)

It means your branch is not rebased with the base. you can do this again after pulling the master branch

It is a little better than before however, you updated the commit-msg again and I was expecting something to be deleted from the go.sum also

![Screenshot from 2021-08-05 14-53-04](https://user-images.githubusercontent.com/22993933/128326659-08aabae9-c899-4b0a-bd22-385572a5a1a0.png)

2021-08-05 09:28 UTC, Haimantika commented
> > > > > The commit-msg looks good to me now. As #1867 is merged you can rebase and make appropriate changes. We will run CI after that.
> > > > 
> > > > 
> > > > I did this yesterday itself.
> > > 
> > > 
> > > We no longer need glide.yaml, moreover you need to make changes to go.mod and go.sum
> > 
> > 
> > Does it look good now?
> > However why am I seeing this? Will this affect in any way?
> > ![Capture](https://user-images.githubusercontent.com/32809211/128324824-9f0787b5-6220-4be4-862f-9eb37ab0fd74.PNG)
> 
> It means your branch is not rebased with the base. you can do this again after pulling the master branch
> 
> It is a little better than before however, you updated the commit-msg again and I was expecting something to be deleted from the go.sum also. you can try to run go mod tidy
> 
> ![Screenshot from 2021-08-05 14-53-04](https://user-images.githubusercontent.com/22993933/128326659-08aabae9-c899-4b0a-bd22-385572a5a1a0.png)

Oh yes. That is after the commit I made, will ammend it. The go.sum file is such after running go mod tidy.

2021-08-06 11:51 UTC, iamniting commented
@Haimantika Can you pls correct the changes so we can take this to closure?

2021-08-06 12:17 UTC, Haimantika commented
> @Haimantika Can you pls correct the changes so we can take this to closure?

I accidently removed the main.go file from the GitHub UI, which is causing a conflict and I am not able to resolve it.

2021-08-06 12:34 UTC, iamniting commented
> > @Haimantika Can you pls correct the changes so we can take this to closure?
> 
> I accidently removed the main.go file from the GitHub UI, which is causing a conflict and I am not able to resolve it.

You can do

`git reset --soft HEAD~1`
`git reset main.go`
`git checkout main.go`

and run `git commit` after it to commit the changes

2021-08-06 12:48 UTC, Haimantika commented
> > > @Haimantika Can you pls correct the changes so we can take this to closure?
> > 
> > 
> > I accidently removed the main.go file from the GitHub UI, which is causing a conflict and I am not able to resolve it.
> 
> You can do
> 
> `git reset --soft HEAD~1`
> `git reset main.go`
> `git checkout main.go`
> 
> and run `git commit` after it to commit the changes

Thanks! It is done. The second commit has the required changes.

2021-08-06 13:02 UTC, iamniting commented
> > > > @Haimantika Can you pls correct the changes so we can take this to closure?
> > > 
> > > 
> > > I accidently removed the main.go file from the GitHub UI, which is causing a conflict and I am not able to resolve it.
> > 
> > 
> > You can do
> > `git reset --soft HEAD~1`
> > `git reset main.go`
> > `git checkout main.go`
> > and run `git commit` after it to commit the changes
> 
> Thanks! It is done. The second commit has the required changes.

We can not just merge the 2nd commit, we need to merge the whole PR. you need to squash them.

2021-08-06 13:22 UTC, Haimantika commented
> > > > > @Haimantika Can you pls correct the changes so we can take this to closure?
> > > > 
> > > > 
> > > > I accidently removed the main.go file from the GitHub UI, which is causing a conflict and I am not able to resolve it.
> > > 
> > > 
> > > You can do
> > > `git reset --soft HEAD~1`
> > > `git reset main.go`
> > > `git checkout main.go`
> > > and run `git commit` after it to commit the changes
> > 
> > 
> > Thanks! It is done. The second commit has the required changes.
> 
> We can not just merge the 2nd commit, we need to merge the whole PR. you need to squas

> > > > > @Haimantika Can you pls correct the changes so we can take this to closure?
> > > > 
> > > > 
> > > > I accidently removed the main.go file from the GitHub UI, which is causing a conflict and I am not able to resolve it.
> > > 
> > > 
> > > You can do
> > > `git reset --soft HEAD~1`
> > > `git reset main.go`
> > > `git checkout main.go`
> > > and run `git commit` after it to commit the changes
> > 
> > 
> > Thanks! It is done. The second commit has the required changes.
> 
> We can not just merge the 2nd commit, we need to merge the whole PR. you need to squash them.

Have one commit now, but we have a Dockerfile.

2021-08-06 13:24 UTC, humblec commented
@iamniting jfyi, the  docker build on `master` looks to be broken btw after the commit which removed `glide.yaml` .

2021-08-11 07:25 UTC, iamniting commented
> @iamniting jfyi, the docker build on `master` looks to be broken btw after the commit which removed `glide.yaml` .

@humblec Can you be more specific about which docker build?

2021-08-11 07:30 UTC, iamniting requested changes

2021-08-11 07:30 UTC, iamniting commented on docs/profiling.md
> +    5.50MB  2.75% 86.24%    39.51MB 19.76%  github.com/heketi/heketi/vendor/github.com/golang-jwt/jwt-go.(*Parser).ParseWithClaims
```suggestion
    5.50MB  2.75% 86.24%    39.51MB 19.76%  github.com/heketi/heketi/vendor/github.com/golang-jwt/jwt.(*Parser).ParseWithClaims
```

2021-08-11 11:09 UTC, iamniting commented
@phlogistonjohn The PR is ready now Can you pls run the action?

2021-08-11 12:38 UTC, phlogistonjohn commented
/ok to test

2021-08-11 12:51 UTC, iamniting approved these changes

2021-08-11 12:56 UTC, iamniting commented
I think we can remove the older versions from the action now as they are not fully supported with the `golang-jwt/jwt`

2021-08-11 13:00 UTC, phlogistonjohn commented
> I think we can remove the older versions from the action now as they are not fully supported with the `golang-jwt/jwt`

If the new jwt library breaks on older go versions I am very very reluctant to use it. I *know* that heketi is used on older systems/distributions.

2021-08-11 13:09 UTC, iamniting commented
> > I think we can remove the older versions from the action now as they are not fully supported with the `golang-jwt/jwt`
> 
> If the new jwt library breaks on older go versions I am very very reluctant to use it. I _know_ that heketi is used on older systems/distributions.

agreed

2021-08-11 17:57 UTC, dims commented
@phlogistonjohn unfortunately form3tech-oss/jwt-go is out of business :(

![image](https://user-images.githubusercontent.com/23304/129078694-806f5967-92eb-49d3-87f8-d010eded8fd3.png)

https://endoflife.date/go shows golang 1.2.x/1.3.x/1.4.x all out of support. 1.4.x went away about 18 months ago. Does heketi need support all the way back to 1.2? we could investigate that, but seems daunting task.

one obvious thing that showed up was that support for Ed25519 is absent in `form3tech-oss/jwt-go` and was added in `golang-jwt/jwt`

2021-08-12 15:01 UTC, phlogistonjohn commented
> @phlogistonjohn unfortunately form3tech-oss/jwt-go is out of business :( - https://github.com/form3tech-oss/jwt-go shows
> 
> ![image](https://user-images.githubusercontent.com/23304/129078694-806f5967-92eb-49d3-87f8-d010eded8fd3.png)
> 

OK, that's something for sure. In my defense I do believe that was changed recently, after this PR was filed. :-)



> https://endoflife.date/go shows golang 1.12.x/1.13.x/1.14.x all out of support. 1.14.x went away about 18 months ago. 

Yes, that's right and we're aware of it.


> Does heketi need support all the way back to 1.12? we could investigate that, but seems daunting task.
> 

We know we support users on centos 7.  I've recently responded to users complaining about issues related to centos 7. Now, its true that one could "install" Go from the tarball releases, but we're also aware that not everyone can just pull stuff from the internet. So I am a bit concerned about cutting them off.

> one obvious thing that showed up was that support for Ed25519 is absent in `form3tech-oss/jwt-go` and was added in `golang-jwt/jwt`

Yeah, that looks like the main thing breaking the build on the older versions.

One of the main drivers of any of the work we do on heketi is security. So there's a clear impetus to take these new versions of Go and jwt library, it just worries me that the language/toolchain and library don't sync well with our legacy use case here in heketi.

Since users on centos 7 and the like can still build heketi with non-packaged versions of Go, use heketi from a container, or take a heketi binary we provide (and we plan on fixing issues wrt that for the next release) I don't think this is a change we should  neglect, but I think I've also made it clear that this isn't a trivial decision.

Thanks for your feedback.

2021-08-17 14:02 UTC, phlogistonjohn commented
We've removed the older go versions from the CI. Please rebase again, thanks.

2021-08-17 18:52 UTC, raghavendra-talur approved these changes

2021-08-20 13:24 UTC, phlogistonjohn commented
/retest this please

2021-08-23 16:31 UTC, phlogistonjohn approved these changes
Tests are now passing, changes are acceptable (see previous discussions), I think we ought to take this.

2021-08-24 06:28 UTC, humblec commented
> Tests are now passing, changes are acceptable (see previous discussions), I think we ought to take this.

Awesome..  Thanks !

2021-08-24 13:39 UTC, merged